[package]
name = "lomen-cli"
version = "0.1.0"
edition = "2024"

#[[bin]]
#name = "lomen"
#path = "src/main.rs"

[dependencies]
argh = "0.1"
libloading = "0.9.0"

[build-dependencies]
embed-manifest = "1.3.1" # for admin rights elevation. see build.rs